import { ThemeProvider } from "@/src/theme/ThemeProvider";
import "./globals.css";
import Header from "@/src/features/layout/Header";
import { Footer } from "@/src/features/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="h-full">
      <body className="bg-background h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            <Header />
            <div className="flex-1 m-auto max-w-xl py-14 w-full">
              {children}
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
