import { Header } from "@/src/features/Header";
import "./globals.css";
import { Footer } from "@/src/features/Footer";

export const metadata = {
  title: "Githread",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/images/favicon.ico',
        href: '/images/favicon.ico',
      },
    ],
  },
};

const RootLayout = ({ children }) => {
  return (
    <html lang="fr" className="h-full">
      <body className="h-full bg-background">
        <div className="flex flex-col">
          <Header />
          <div className="m-auto mt-10 w-full max-w-2xl flex-1 py-14">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
